In [1]:
import pandas as pd
import json

In [2]:
f=open("linux_tactics.json",'r')
jsondata=json.load(f)
f.close()

In [3]:
tactickeys=jsondata.keys()
tactics=[]
for i in tactickeys:
    tactics.append(i)

In [4]:
maxlen=0
for i in tactics:
    if len(jsondata[i])>maxlen:
        maxlen=len(jsondata[i])
print(maxlen)

20

In [5]:
for i in tactics:
    while len(jsondata[i])!=maxlen:
        jsondata[i].append(" ")

In [6]:
df=pd.DataFrame(jsondata,columns=tactics)

In [7]:
df

,Credential Access,Command And Control,Initial Access,Discovery,Execution,Exfiltration,Collection,Defense Evasion,Persistence,Privilege Escalation,Lateral Movement,Impact
0,T1003:36,T1071:30,T1193:37,T1087:12,T1064:41,T1002:22,T1119:7,T1064:41,T1078:25,T1078:25,T1105:30,T1487:3
1,T1110:8,T1105:30,T1078:25,T1046:11,T1204:37,T1041:8,T1213:2,T1027:36,T1100:9,T1055:12,T1021:6,T1486:3
2,T1081:7,T1043:19,T1192:20,T1040:3,T1059:32,T1048:6,,T1078:25,T1108:7,T1100:9,T1210:2,T1485:2
3,T1040:3,T1102:12,T1189:14,T1201:1,T1203:18,T1030:1,,T1036:19,T1136:5,T1068:8,T1072:1,T1492:2
4,T1503:3,T1032:11,T1194:4,,T1072:1,,,T1102:12,T1067:3,,T1017:1,T1488:1
5,,T1090:10,T1190:3,,,,,T1055:12,T1176:2,,,T1494:1
6,,T1065:8,T1199:2,,,,,T1090:10,,,,T1493:1
7,,T1219:5,T1195:2,,,,,T1089:9,,,,
8,,T1132:5,,,,,,T1070:8,,,,
9,,T1094:4,,,,,,T1108:7,,,,
10,,T1024:3,,,,,,T1480:2,,,,
11,,T1095:3,,,,,,T1211:1,,,,
12,,T1008:3,,,,,,T1146:1,,,,
13,,T1001:2,,,,,,,,,,
14,,T1188:2,,,,,,,,,,
15,,T1104:2,,,,,,,,,,
16,,T1092:1,,,,,,,,,,
17,,T1172:1,,,,,,,,,,
18,,T1026:1,,,,,,,,,,
19,,T1483:1,,,,,,,,,,

In [8]:
f=open("windows_tactics.json",'r')
jsondata=json.load(f)
f.close()

In [9]:
tactickeys=jsondata.keys()
tactics=[]
for i in tactickeys:
    tactics.append(i)

In [10]:
maxlen=0
for i in tactics:
    if len(jsondata[i])>maxlen:
        maxlen=len(jsondata[i])
print(maxlen)

30

In [11]:
for i in tactics:
    while len(jsondata[i])!=maxlen:
        jsondata[i].append(" ")

In [12]:
df=pd.DataFrame(jsondata,columns=tactics)
df

,Persistence,Privilege Escalation,Credential Access,Command And Control,Initial Access,Lateral Movement,Discovery,Execution,Exfiltration,Collection,Defense Evasion,Impact
0,T1078:25,T1078:25,T1003:36,T1071:30,T1193:37,T1105:30,T1087:12,T1064:41,T1002:22,T1114:7,T1064:41,T1487:3
1,T1053:24,T1053:24,T1110:8,T1105:30,T1078:25,T1076:17,T1046:11,T1204:37,T1041:8,T1119:7,T1027:36,T1486:3
2,T1133:10,T1055:12,T1081:7,T1043:19,T1192:20,T1077:9,T1040:3,T1086:36,T1048:6,T1213:2,T1078:25,T1485:2
3,T1050:10,T1050:10,T1098:4,T1102:12,T1189:14,T1021:6,T1201:1,T1059:32,T1030:1,,T1036:19,T1492:2
4,T1100:9,T1100:9,T1040:3,T1032:11,T1133:10,T1075:5,,T1053:24,,,T1102:12,T1488:1
5,T1023:8,T1068:8,T1503:3,T1090:10,T1194:4,T1097:4,,T1203:18,,,T1055:12,T1489:1
6,T1108:7,T1088:8,T1187:2,T1065:8,T1190:3,T1210:2,,T1047:14,,,T1112:11,T1494:1
7,T1015:5,T1015:5,T1141:1,T1219:5,T1091:2,T1037:2,,T1173:8,,,T1045:11,T1493:1
8,T1136:5,T1134:3,T1214:1,T1132:5,T1199:2,T1091:2,,T1085:8,,,T1090:10,
9,T1098:4,T1038:2,,T1094:4,T1195:2,T1080:1,,T1117:6,,,T1143:9,
10,T1031:4,T1504:1,,T1024:3,,T1028:1,,T1035:5,,,T1089:9,
11,T1067:3,T1138:1,,T1095:3,,T1072:1,,T1223:5,,,T1073:9,
12,T1084:3,T1182:1,,T1008:3,,T1017:1,,T1106:4,,,T1070:8,
13,T1037:2,,,T1001:2,,T1175:1,,T1170:4,,,T1085:8,
14,T1137:2,,,T1188:2,,,,T1218:3,,,T1088:8,
15,T1004:2,,,T1104:2,,,,T1191:2,,,T1108:7,
16,T1038:2,,,T1092:1,,,,T1028:1,,,T1117:6,
17,T1176:2,,,T1172:1,,,,T1072:1,,,T1223:5,
18,T1504:1,,,T1026:1,,,,T1216:1,,,T1221:4,
19,T1138:1,,,T1483:1,,,,T1175:1,,,T1170:4,
20,T1197:1,,,,,,,T1220:1,,,T1134:3,
21,T1182:1,,,,,,,,,,T1218:3,
22,,,,,,,,,,,T1480:2,
23,,,,,,,,,,,T1038:2,
24,,,,,,,,,,,T1191:2,
25,,,,,,,,,,,T1211:1,
26,,,,,,,,,,,T1096:1,
27,,,,,,,,,,,T1216:1,
28,,,,,,,,,,,T1197:1,
29,,,,,,,,,,,T1220:1,